# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/resources/v1/ingredient.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main/resources/v1/ingredient.proto", :syntax => :proto3) do
    add_message "main.resources.v1.Ingredient" do
      optional :name, :string, 1
      optional :quantity, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Main
  module Resources
    module V1
      Ingredient = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.resources.v1.Ingredient").msgclass
    end
  end
end
