# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/resources/v1/step.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main/resources/v1/step.proto", :syntax => :proto3) do
    add_message "main.resources.v1.Step" do
      optional :description, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
    end
  end
end

module Main
  module Resources
    module V1
      Step = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.resources.v1.Step").msgclass
    end
  end
end
