# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: main/services/v1/recipe.proto for package 'main.services.v1'

require 'grpc'
require 'main/services/v1/recipe_pb'

module Main
  module Services
    module V1
      module Recipe
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'main.services.v1.Recipe'

          rpc :GetRecipe, GetRecipeRequest, GetRecipeResponse
          rpc :ListRecipes, ListRecipesRequest, ListRecipesResponse
          rpc :CreateRecipe, CreateRecipeRequest, CreateRecipeResponse
          rpc :DeleteRecipe, DeleteRecipeRequest, DeleteRecipeResponse
          rpc :ListRecipesByUser, ListRecipesByUsersRequest, ListRecipesByUserResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
