# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/services/v1/recipe.proto

require 'google/protobuf'

require 'main/resources/v1/recipe_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main/services/v1/recipe.proto", :syntax => :proto3) do
    add_message "main.services.v1.GetRecipeRequest" do
      optional :id, :uint64, 1
    end
    add_message "main.services.v1.GetRecipeResponse" do
      optional :recipe, :message, 1, "main.resources.v1.Recipe"
    end
    add_message "main.services.v1.ListRecipesRequest" do
      optional :page, :uint32, 1
      optional :per_page, :uint32, 2
    end
    add_message "main.services.v1.ListRecipesResponse" do
      repeated :recipes, :message, 1, "main.resources.v1.Recipe"
    end
    add_message "main.services.v1.CreateRecipeRequest" do
      optional :recipe, :message, 1, "main.resources.v1.Recipe"
    end
    add_message "main.services.v1.CreateRecipeResponse" do
      optional :recipe, :message, 1, "main.resources.v1.Recipe"
    end
    add_message "main.services.v1.DeleteRecipeRequest" do
      optional :id, :uint64, 1
    end
    add_message "main.services.v1.DeleteRecipeResponse" do
    end
    add_message "main.services.v1.ListRecipesByUsersRequest" do
      optional :page, :uint32, 1
      optional :per_page, :uint32, 2
      optional :user_id, :uint64, 3
    end
    add_message "main.services.v1.ListRecipesByUserResponse" do
      repeated :recipes, :message, 1, "main.resources.v1.Recipe"
    end
  end
end

module Main
  module Services
    module V1
      GetRecipeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.GetRecipeRequest").msgclass
      GetRecipeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.GetRecipeResponse").msgclass
      ListRecipesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.ListRecipesRequest").msgclass
      ListRecipesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.ListRecipesResponse").msgclass
      CreateRecipeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.CreateRecipeRequest").msgclass
      CreateRecipeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.CreateRecipeResponse").msgclass
      DeleteRecipeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.DeleteRecipeRequest").msgclass
      DeleteRecipeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.DeleteRecipeResponse").msgclass
      ListRecipesByUsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.ListRecipesByUsersRequest").msgclass
      ListRecipesByUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.services.v1.ListRecipesByUserResponse").msgclass
    end
  end
end
