# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/resources/v1/recipe.proto

require 'google/protobuf'

require 'main/resources/v1/user_pb'
require 'main/resources/v1/ingredient_pb'
require 'main/resources/v1/step_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main/resources/v1/recipe.proto", :syntax => :proto3) do
    add_message "main.resources.v1.Recipe" do
      optional :id, :uint64, 1
      optional :user, :message, 2, "main.resources.v1.User"
      repeated :ingredients, :message, 3, "main.resources.v1.Ingredient"
      repeated :steps, :message, 4, "main.resources.v1.Step"
      optional :title, :string, 5
      optional :description, :string, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
  end
end

module Main
  module Resources
    module V1
      Recipe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("main.resources.v1.Recipe").msgclass
    end
  end
end
