# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsukurepo_backend/services/v1/tsukurepo.proto

require 'google/protobuf'

require 'tsukurepo_backend/resources/v1/tsukurepo_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tsukurepo_backend/services/v1/tsukurepo.proto", :syntax => :proto3) do
    add_message "tsukurepo_backend.services.v1.GetTsukurepoRequest" do
      optional :id, :uint64, 1
    end
    add_message "tsukurepo_backend.services.v1.GetTsukurepoResponse" do
      optional :tsukurepo, :message, 1, "tsukurepo_backend.resources.v1.Tsukurepo"
    end
    add_message "tsukurepo_backend.services.v1.ListTsukureposRequest" do
      optional :page, :uint32, 1
      optional :per_page, :uint32, 2
    end
    add_message "tsukurepo_backend.services.v1.ListTsukureposResponse" do
      repeated :tsukurepos, :message, 1, "tsukurepo_backend.resources.v1.Tsukurepo"
    end
    add_message "tsukurepo_backend.services.v1.CreateTsukurepoRequest" do
      optional :tsukurepo, :message, 1, "tsukurepo_backend.resources.v1.Tsukurepo"
    end
    add_message "tsukurepo_backend.services.v1.CreateTsukurepoResponse" do
      optional :tsukurepo, :message, 1, "tsukurepo_backend.resources.v1.Tsukurepo"
    end
    add_message "tsukurepo_backend.services.v1.DeleteTsukurepoRequest" do
      optional :id, :uint64, 1
    end
    add_message "tsukurepo_backend.services.v1.DeleteTsukurepoResponse" do
    end
  end
end

module TsukurepoBackend
  module Services
    module V1
      GetTsukurepoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.GetTsukurepoRequest").msgclass
      GetTsukurepoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.GetTsukurepoResponse").msgclass
      ListTsukureposRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.ListTsukureposRequest").msgclass
      ListTsukureposResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.ListTsukureposResponse").msgclass
      CreateTsukurepoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.CreateTsukurepoRequest").msgclass
      CreateTsukurepoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.CreateTsukurepoResponse").msgclass
      DeleteTsukurepoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.DeleteTsukurepoRequest").msgclass
      DeleteTsukurepoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.services.v1.DeleteTsukurepoResponse").msgclass
    end
  end
end
