# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsukurepo_backend/resources/v1/tsukurepo.proto

require 'google/protobuf'

require 'main/resources/v1/user_pb'
require 'main/resources/v1/recipe_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tsukurepo_backend/resources/v1/tsukurepo.proto", :syntax => :proto3) do
    add_message "tsukurepo_backend.resources.v1.Tsukurepo" do
      optional :id, :uint64, 1
      optional :recipe_id, :uint64, 2
      optional :user_id, :uint64, 3
      optional :comment, :string, 4
      optional :user, :message, 5, "main.resources.v1.User"
      optional :recipe, :message, 6, "main.resources.v1.Recipe"
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
  end
end

module TsukurepoBackend
  module Resources
    module V1
      Tsukurepo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tsukurepo_backend.resources.v1.Tsukurepo").msgclass
    end
  end
end
